# Configuration file to run tests on Travis-CI via GitHub notifications
# See http://travis-ci.org/

language: python
python:
# No skiptest in 2.6 so ignore for now
#  - "2.6"
  - "2.7"

install:
  - "pip install ."

script:
# Run the unit tests for bcftbx
  - "python setup.py test"

